@@ .. @@
     id,
     first_name,
     last_name,
     email,
     phone,
     password_hash,
     role,
     is_active,
     created_at,
     last_login,
     profile_image,
     vip_expiry_date,
     vehicle_make,
     vehicle_model,
     vehicle_year,
     vehicle_plate,
     vehicle_color,
     total_trips,
     total_earnings,
     rating
 ) VALUES (
     gen_random_uuid()::text,
     'José',
     'López',
     'p.joselopez17@gmail.com',
     '8098522664',
-    'sofia24@',
+    'Sofia24@123',
     'admin',
     true,
     NOW(),
     NOW(),